version: '3.7'

services:
  nginx:
    build: ./hokbu-nginx
    volumes:
      - "./6-kiatko:/kiatko:ro"
    networks:
      - default
      - nginx-bridge
    environment:
      - VIRTUAL_HOST=hapsing.ithuan.tw
      - LETSENCRYPT_HOST=hapsing.ithuan.tw
      - LETSENCRYPT_EMAIL=ithuan@ithuan.tw
    restart: always
  hapsing:
    build: ./hokbu-khuanking
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - DEVICE=${DEVICE:-gpu}
      - CUDA_VISIBLE_DEVICES=${CUDA_VISIBLE_DEVICES:-all}
      - VOCODER=${VOCODER:-wavernn}
      - BATCHED=${BATCHED:-batched}
      - TARGET=${TARGET:-2000}
      - OVERLAP=${OVERLAP:-400}
      - GL_ITERS=${GL_ITERS:-32}
    volumes:
      - "./tshamsoo/hparams.py:/WaveRNN/hparams.py:ro"
      - "./tshamsoo/text_init.py:/WaveRNN/utils/text/__init__.py:ro"
      - "./tshamsoo/text_symbols.py:/WaveRNN/utils/text/symbols.py:ro"
      - "./0.2.1-checkpoints:/WaveRNN/checkpoints"
      - "./6-kiatko:/kiatko"
    healthcheck:
      test: nvidia-smi || exit 1
      start_period: 60s
      interval: 20s
      timeout: 10s
      retries: 2
    restart: always

networks:
  nginx-bridge:
    external: true
