version: '3.7'

services:
  nginx:
    build: ./hokbu-nginx
    volumes:
      - "./6-kiatko:/kiatko:ro"
    networks:
      - default
      - nginx-bridge
    environment:
      - VIRTUAL_HOST=hapsing.ithuan.tw
      - LETSENCRYPT_HOST=hapsing.ithuan.tw
      - LETSENCRYPT_EMAIL=ithuan@ithuan.tw
    restart: always
  hapsing:
    build: ./hokbu-khuanking
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      # - CUDA_VISIBLE_DEVICES=all
      - CUDA_VISIBLE_DEVICES=0
      # - VOCODER=griffinlim
      - TARGET=2000
      - OVERLAP=400
      # - FORCE_CPU=True
    volumes:
      - "./tshamsoo/hparams.py:/WaveRNN/hparams.py:ro"
      - "./tshamsoo/text_init.py:/WaveRNN/utils/text/__init__.py:ro"
      - "./tshamsoo/text_symbols.py:/WaveRNN/utils/text/symbols.py:ro"
      - "./0.2.1-checkpoints:/WaveRNN/checkpoints"
      - "./6-kiatko:/kiatko"
    restart: always

networks:
  nginx-bridge:
    external: true
