version: '3.7'

services:
  habsang:
    build: ./hokbu-khuanking
    environment:
      CUDA_VISIBLE_DEVICES: "all"
      # FORCE_CPU: "True"
    ports:
      - "5000:5000"
    volumes:
      - "./tshamsoo/hparams.py:/WaveRNN/hparams.py:ro"
      - "./tshamsoo/text_init.py:/WaveRNN/utils/text/__init__.py:ro"
      - "./tshamsoo/text_symbols.py:/WaveRNN/utils/text/symbols.py:ro"
      - "./0.2.1-checkpoints:/WaveRNN/checkpoints"
      - "./6-kiatko:/kiatko"
    restart: always
