---
version: '3.7'

services:
  nginx-cache:
    image: nginx:1-alpine
    networks:
      - default
      - nginx-bridge
    volumes:
      - "./nginx-cache/default.conf:/etc/nginx/conf.d/default.conf:ro"
      - "nginx_cache_data:/cache"
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST:-hapsing.ithuan.tw}
      - LETSENCRYPT_HOST=${VIRTUAL_HOST:-hapsing.ithuan.tw}
      - LETSENCRYPT_EMAIL=ithuan@ithuan.tw
    restart: always
  hokbu-nginx:
    image: nginx:1-alpine
    networks:
      - default
      - hokbu-bridge
    volumes:
      - "./hokbu-nginx/default.conf:/etc/nginx/conf.d/default.conf:ro"
      - "./6-kiatko:/kiatko:ro"
    restart: always
  hapsing:
    build: ./hokbu-khuanking/
    networks:
      - hokbu-bridge
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - GUNICORN_TIMEOUT=${GUNICORN_TIMEOUT:-60}
      - GUNICORN_WORKERS=${GUNICORN_WORKERS:-6}
      - GUNICORN_MAX_REQUESTS=${GUNICORN_MAX_REQUESTS:-30}
      - GUNICORN_MAX_REQUESTS_JITTER=${GUNICORN_MAX_REQUESTS_JITTER:-10}
      - DEVICE=${DEVICE:-gpu}
      - CUDA_VISIBLE_DEVICES=${CUDA_VISIBLE_DEVICES:-0}
      - VOCODER=${VOCODER:-wavernn}
      - BATCHED=${BATCHED:-batched}
      - TARGET=${TARGET:-2000}
      - OVERLAP=${OVERLAP:-400}
      - GL_ITERS=${GL_ITERS:-32}
      - SENTRY_DSN=${SENTRY_DSN:-}
    volumes:
      - "./tshamsoo/hparams.py:/WaveRNN/hparams.py:ro"
      - "./tshamsoo/text_init.py:/WaveRNN/utils/text/__init__.py:ro"
      - "./tshamsoo/text_symbols.py:/WaveRNN/utils/text/symbols.py:ro"
      - "./0.2.1-checkpoints:/WaveRNN/checkpoints"
      - "./6-kiatko:/kiatko"
    healthcheck:
      test: ["CMD-SHELL", "test -s `which nvidia-smi` && nvidia-smi || exit 1"]
      start_period: 1s
      interval: 20s
      timeout: 5s
      retries: 2
    labels:
      - autoheal=true
      - autoheal.stop.timeout=1
    restart: always
  autoheal:
    image: willfarrell/autoheal
    environment:
      - AUTOHEAL_CONTAINER_LABEL=all
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
  thai-imtong:
    image: alpine:3
    volumes:
      - "./6-kiatko:/kiatko"
      - "./thai-khuanking/15min:/etc/periodic/15min/:ro"
    command: crond -f -l 0 -L -

volumes:
  nginx_cache_data:

networks:
  nginx-bridge:
    external: true
  hokbu-bridge:
