FROM i3thuan5/hapsing-giliau AS giliau

RUN pip install --upgrade https://github.com/i3thuan5/tai5-uan5_gian5-gi2_hok8-bu7/archive/Tacotron%E8%8E%AB%E6%8F%9B%E9%80%9D.zip

CMD python manage.py 匯出Tacotron格式資料 台語 王秀容 /opt/giliau

